#!/usr/bin/env python3
"""Block atlas for the voxel planet, built from the local Minecraft jar (nothing of Mojang's in the repo).

64x64, 4x4 tiles of 16x16, in the order of fabric voxel/Material: 0 grass top, 1 grass side,
2 dirt, 3 stone, 4 bedrock. Grass is tinted with the plains color, as Minecraft does at runtime.
Written as a GX RGB565 texture (4x4 texel blocks, big-endian) in a C header:

  voxel_atlas.py OUT.h [--png PREVIEW.png]
"""
import io
import os
import sys
import zipfile

from PIL import Image

MC_JAR = os.path.expanduser("~/.gradle/caches/fabric-loom/26.3/minecraft-client.jar")
BLOCKS = "assets/minecraft/textures/block/"
PLAINS = (0x91, 0xBD, 0x59)
SIZE, TILE = 64, 16


def tinted(img, color):
    img = img.convert("RGBA")
    out = Image.new("RGBA", img.size)
    src, dst = img.load(), out.load()
    for y in range(img.height):
        for x in range(img.width):
            r, g, b, a = src[x, y]
            dst[x, y] = (r * color[0] // 255, g * color[1] // 255, b * color[2] // 255, a)
    return out


def tiles(jar):
    read = lambda name: Image.open(io.BytesIO(jar.read(BLOCKS + name))).convert("RGBA").crop((0, 0, TILE, TILE))
    side = read("grass_block_side.png")
    side.alpha_composite(tinted(read("grass_block_side_overlay.png"), PLAINS))
    return [tinted(read("grass_block_top.png"), PLAINS), side, read("dirt.png"), read("stone.png"), read("bedrock.png")]


def atlas(tile_list):
    img = Image.new("RGBA", (SIZE, SIZE), (0, 0, 0, 255))
    for n, t in enumerate(tile_list):
        img.paste(t, (n % 4 * TILE, n // 4 * TILE))
    return img


def rgb565_tiled(img):
    """GX RGB565: 4x4 texel blocks left to right, top to bottom; texels row-major in a block."""
    px = img.convert("RGB").load()
    out = bytearray()
    for by in range(0, img.height, 4):
        for bx in range(0, img.width, 4):
            for y in range(by, by + 4):
                for x in range(bx, bx + 4):
                    r, g, b = px[x, y]
                    v = (r >> 3) << 11 | (g >> 2) << 5 | b >> 3
                    out += v.to_bytes(2, "big")
    return bytes(out)


def header(data):
    return ("// Generated by tools/voxel_atlas.py from the local Minecraft jar.\n"
            f"#define GXC_ATLAS_SIZE {SIZE}\n"
            f"__attribute__((aligned(32))) u8 gVoxelAtlas[{len(data)}] = {{{','.join(map(str, data))}}};\n")


def main(argv):
    if len(argv) not in (2, 4):
        raise SystemExit(__doc__)
    with zipfile.ZipFile(MC_JAR) as jar:
        img = atlas(tiles(jar))
    os.makedirs(os.path.dirname(os.path.abspath(argv[1])), exist_ok=True)
    with open(argv[1], "w") as f:
        f.write(header(rgb565_tiled(img)))
    if len(argv) == 4 and argv[2] == "--png":
        img.save(argv[3])


if __name__ == "__main__":
    main(sys.argv)
