#!/usr/bin/env python3
"""Block atlas for the voxel planet, built from the local Minecraft jar (nothing of Mojang's in the repo).

64x64, 4x4 tiles of 16x16, in the order of fabric voxel/Material: 0 grass top, 1 grass side,
2 dirt, 3 stone, 4 bedrock, 5 ice, 6 water, 7 lava, 8 cobblestone, 9 obsidian. Grass and water are
tinted with the plains colors, as Minecraft does at runtime; fluids use their first animation frame.
Written as a GX RGB565 texture (4x4 texel blocks, big-endian) with its mipmaps (64, 32, 16 and
8 texels wide: tiles of 16, 8, 4 and 2, each averaged within its own tile) in a C header:

  voxel_atlas.py OUT.h [--png PREVIEW.png]
"""
import io
import os
import sys
import zipfile

from PIL import Image

MC_JAR = os.path.expanduser("~/.gradle/caches/fabric-loom/26.3/minecraft-client.jar")
BLOCKS = "assets/minecraft/textures/block/"
PLAINS = (0x91, 0xBD, 0x59)
WATER = (0x3F, 0x76, 0xE4)
SIZE, TILE = 64, 16
LEVELS = 4


def tinted(img, color):
    img = img.convert("RGBA")
    out = Image.new("RGBA", img.size)
    src, dst = img.load(), out.load()
    for y in range(img.height):
        for x in range(img.width):
            r, g, b, a = src[x, y]
            dst[x, y] = (r * color[0] // 255, g * color[1] // 255, b * color[2] // 255, a)
    return out


def tiles(jar):
    read = lambda name: Image.open(io.BytesIO(jar.read(BLOCKS + name))).convert("RGBA").crop((0, 0, TILE, TILE))
    side = read("grass_block_side.png")
    side.alpha_composite(tinted(read("grass_block_side_overlay.png"), PLAINS))
    return [tinted(read("grass_block_top.png"), PLAINS), side, read("dirt.png"), read("stone.png"), read("bedrock.png"),
            read("ice.png"), tinted(read("water_still.png"), WATER), read("lava_still.png"), read("cobblestone.png"),
            read("obsidian.png")]


def atlas(tile_list):
    img = Image.new("RGBA", (SIZE, SIZE), (0, 0, 0, 255))
    for n, t in enumerate(tile_list):
        img.paste(t, (n % 4 * TILE, n // 4 * TILE))
    return img


def rgb565_tiled(img):
    """GX RGB565: 4x4 texel blocks left to right, top to bottom; texels row-major in a block."""
    px = img.convert("RGB").load()
    out = bytearray()
    for by in range(0, img.height, 4):
        for bx in range(0, img.width, 4):
            for y in range(by, by + 4):
                for x in range(bx, bx + 4):
                    r, g, b = px[x, y]
                    v = (r >> 3) << 11 | (g >> 2) << 5 | b >> 3
                    out += v.to_bytes(2, "big")
    return bytes(out)


def mipmaps(img):
    """Each level halves the last one tile by tile, so no tile ever blends into its neighbor."""
    levels = [img.convert("RGB")]
    for _ in range(LEVELS - 1):
        prev = levels[-1]
        levels.append(prev.resize((prev.width // 2, prev.height // 2), Image.BOX))
    return levels


def header(data):
    return ("// Generated by tools/voxel_atlas.py from the local Minecraft jar.\n"
            f"#define GXC_ATLAS_SIZE {SIZE}\n"
            f"#define GXC_ATLAS_LEVELS {LEVELS}\n"
            f"__attribute__((aligned(32))) u8 gVoxelAtlas[{len(data)}] = {{{','.join(map(str, data))}}};\n")


def main(argv):
    if len(argv) not in (2, 4):
        raise SystemExit(__doc__)
    with zipfile.ZipFile(MC_JAR) as jar:
        img = atlas(tiles(jar))
    os.makedirs(os.path.dirname(os.path.abspath(argv[1])), exist_ok=True)
    with open(argv[1], "w") as f:
        f.write(header(b"".join(rgb565_tiled(level) for level in mipmaps(img))))
    if len(argv) == 4 and argv[2] == "--png":
        img.save(argv[3])


if __name__ == "__main__":
    main(sys.argv)
